=== HimarRH/ActividadesLenguajes/Actividad2/biblioteca.dtd
<!--NODO PRINCIPAL BIBLIOTECA-->
<!ELEMENT biblioteca (libros, revistas, periodicos)>

<!--NODO LIBROS-->
<!ELEMENT libros (libro+)>

<!--NODO LIBRO-->
<!ELEMENT libro (titulo, capitulos, indice, sinopsis)>
<!ATTLIST libro id ID #REQUIRED>
<!ATTLIST libro tipo_clase (novela | infantil | didactico) #REQUIRED>
<!ATTLIST libro num_pag CDATA #REQUIRED>

<!--ELEMENTOS DE LIBRO-->
<!ELEMENT capitulos (capitulo+)>
<!ELEMENT capitulo (titulo_cap+, contenido+)>
<!ATTLIST capitulo num_pag CDATA "1">
<!ELEMENT titulo_cap (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>

<!--NODO REVISTAS-->
<!ELEMENT revistas (revista+)>

<!--NODO REVISTA-->
<!ELEMENT revista (titulo, numero_revista, indice, secciones)>
<!ATTLIST revista id ID #REQUIRED>
<!ATTLIST revista tipo_clase (informatica | corazon | coches | investigacion) #REQUIRED>
<!ATTLIST revista num_pag CDATA #REQUIRED>

<!--ELEMENTOS REVISTA-->
<!ELEMENT numero_revista (#PCDATA)>

<!--NODO PERIODICOS-->
<!ELEMENT periodicos (periodico+)>

<!--NODO PERIODICO-->
<!ELEMENT periodico (secciones+, indice+)>
<!ATTLIST periodico id ID #REQUIRED>
<!ATTLIST periodico tipo_clase (nacional | internacional) #REQUIRED>
<!ATTLIST periodico fecha_publicacion CDATA #REQUIRED>

<!--ELEMENTOS COMUNES-->
<!ELEMENT indice (#PCDATA)>

<!--Libros + revistas-->
<!ELEMENT titulo (#PCDATA)>

<!--revistas + periodicos-->
<!ELEMENT secciones (seccion+)>
<!ELEMENT seccion (titulo_sec?, articulo?, contenido)>
<!ATTLIST seccion num_pag CDATA "1">
<!ELEMENT titulo_sec (#PCDATA)>
<!ATTLIST seccion tipo_sec (opinion | deportes) #IMPLIED>
<!ELEMENT articulo (#PCDATA)>
<!ATTLIST articulo autor CDATA #REQUIRED>
<!ELEMENT contenido EMPTY>
<!ATTLIST contenido enlace CDATA #REQUIRED>

=== HimarRH/ActividadesLenguajes/Actividad2/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">
<biblioteca>
    <libros>
        <libro id="L0001" tipo_clase="novela" num_pag="672">
            <titulo>Juego de Tronos</titulo>
            <capitulos>
                <capitulo num_pag="100">
                    <titulo_cap>Capitulo 1</titulo_cap>
                    <contenido enlace=""/>
                </capitulo>
            </capitulos>
            <indice></indice>
            <sinopsis>
                Juego de tronos es la historia de la lucha por un trono, el trono de hierro, 
                forjado con las espadas de los enemigos vencidos. 
                Siete son los reinos de Poniente y muchas las casas que se disputarán la corona: 
                los herederos, los exiliados, los despojados y los actuales regentes.
            </sinopsis>
        </libro>
        <libro id="L0002" tipo_clase="infantil" num_pag="120">
            <titulo>El principito</titulo>
            <capitulos>
                <capitulo num_pag="2">
                    <titulo_cap>Capitulo 1</titulo_cap>
                    <contenido enlace=""/>
                </capitulo>
            </capitulos>
            <indice></indice>
            <sinopsis>
                El principito es una narración corta del escritor francés Antoine de Saint-Exupéry. 
                La historia se centra en un pequeño príncipe que realiza una travesía por el universo. 
                En este viaje descubre la extraña forma en que los adultos ven la vida y comprende el 
                valor del amor y la amistad.
            </sinopsis>
        </libro>
        <libro id="L0003" tipo_clase="didactico" num_pag="208">
            <titulo>La puerta de los tres cerrojos</titulo>
            <capitulos>
                <capitulo num_pag="12">
                    <titulo_cap>Capitulo 1</titulo_cap>
                    <contenido enlace=""/>
                </capitulo>
            </capitulos>
            <indice></indice>
            <sinopsis>
                Después de recibir un misterioso mensaje, Niko recorre un nuevo camino para 
                ir al instituto y descubre una casa que no había visto nunca antes. 
                La resolución de un enigma le permite entrar en lo que resultará ser un extraño 
                lugar donde nacen universos, hay un gato que aparece y desparece, y es posible teleportarse
            </sinopsis>
        </libro>
    </libros>
    <revistas>
        <revista id="R0001" tipo_clase="informatica" num_pag="132">
            <titulo>Computer Hoy</titulo>
            <numero_revista>101</numero_revista>
            <indice></indice>
            <secciones>
                <seccion num_pag="">
                    <titulo_sec>Software</titulo_sec>
                    <contenido enlace=""/>
                </seccion>
            </secciones>
        </revista>
        <revista id="R0002" tipo_clase="coches" num_pag="258">
            <titulo>Autofacil</titulo>
            <numero_revista>20</numero_revista>
            <indice></indice>
            <secciones>
                <seccion num_pag="45">
                    <titulo_sec>Deportes</titulo_sec>
                    <contenido enlace=""/>
                </seccion>
            </secciones>
        </revista>
        <revista id="R0003" tipo_clase="investigacion" num_pag="160">
            <titulo>Revista Española de Física</titulo>
            <numero_revista>17</numero_revista>
            <indice></indice>
            <secciones>
                <seccion num_pag="4">
                    <titulo_sec>La ciencia y los medios de comunicación</titulo_sec>
                    <contenido enlace=""/>
                </seccion>
            </secciones>
        </revista>
    </revistas>
    <periodicos>
        <periodico id="P0001" tipo_clase="internacional" fecha_publicacion="09/05/2023">
            <secciones>
                <seccion tipo_sec="opinion">
                    <articulo autor="Paco">Obviedades</articulo>
                    <contenido enlace=""/>
                </seccion>
            </secciones>
            <indice></indice>
        </periodico>
    </periodicos>
</biblioteca>
